# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20170708_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocation',
            name='timestamp',
            field=models.DateTimeField(default='timezone.now'),
        ),
    ]
