# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurantlocation_my_date_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocation',
            name='my_date_field',
            field=models.DateField(),
        ),
    ]
