# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_remove_restaurantlocation_my_date_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='my_date_field',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
